# 四星角色
commonCharacters:
  # 蒙德地区
  - 
    id: 10001
    name:
      - 安柏
      - 飞行冠军
  - 
    id: 10002
    name:
      - 凯亚
      - 寒风剑士
  - 
    id: 10003
    name:
      - 丽莎
      - 蔷薇魔女
  - 
    id: 10004
    name:
      - 芭芭拉
      - 闪耀偶像
  - 
    id: 10005
    name:
      - 砂糖
      - 无害甜度
  - 
    id: 10006
    name:
      - 迪奥娜
      - 猫尾特调
  - 
    id: 10007
    name:
      - 诺艾尔
      - 未授勋之花
  - 
    id: 10008
    name:
      - 雷泽
      - 狼少年
  - 
    id: 10009
    name:
      - 菲谢尔
      - 断罪皇女
  - 
    id: 10010
    name:
      - 班尼特
      - 命运试金石
  - 
    id: 10011
    name:
      - 罗莎莉亚
      - 棘冠恩典
  # 璃月地区
  - 
    id: 10012
    name:
      - 香菱
      - 万民百味
  - 
    id: 10013
    name:
      - 凝光
      - 掩月天权
  - 
    id: 10014
    name:
      - 北斗
      - 无冕的龙王
  - 
    id: 10015
    name:
      - 辛焱
      - 燥热旋律
  - 
    id: 10016
    name:
      - 行秋
      - 少年春衫薄
  - 
    id: 10017
    name:
      - 重云
      - 雪融有踪
  - 
    id: 10018
    name:
      - 烟绯
      - 智明无邪
  - 
    id: 10019
    name:
      - 云堇
      - 红毹婵娟
  # 稻妻地区
  - 
    id: 10020
    name:
      - 托马
      - 渡来介者
  - 
    id: 10021
    name:
      - 九条裟罗
      - 黑羽鸣镝
  - 
    id: 10022
    name:
      - 五郎
      - 戎犬锵锵
  - 
    id: 10023
    name:
      - 早柚
      - 忍里之貂
  - 
    id: 10024
    name:
      - 久岐忍
      - 烦恼刈除
  - 
    id: 10025
    name:
      - 鹿野院平藏
      - 心朝乂安

# 五星角色
rareCharacters:
  - 
    id: 20001
    name:
      - 空
  - 
    id: 20002
    name:
      - 荧
  - 
    id: 20027
    name:
      - 埃洛伊
      - 异界的救世主
  # 蒙德地区
  - 
    id: 20003
    name:
      - 温迪
      - 风色诗人
  - 
    id: 20004
    name:
      - 琴
      - 蒲公英骑士
  - 
    id: 20005
    name:
      - 迪卢克
      - 晨曦的暗面
  - 
    id: 20006
    name:
      - 莫娜
      - 星天水镜
  - 
    id: 20007
    name:
      - 阿贝多
      - 白垩之子
  - 
    id: 20008
    name:
      - 可莉
      - 逃跑的太阳
  - 
    id: 20009
    name:
      - 优菈
      - 浪沫的旋舞
  # 璃月地区
  - 
    id: 20010
    name:
      - 申鹤
      - 孤辰茕怀
  - 
    id: 20011
    name:
      - 刻晴
      - 霆霓快雨
  - 
    id: 20012
    name:
      - 七七
      - 冻冻回魂夜
  - 
    id: 20013
    name:
      - 钟离
      - 尘世闲游
  - 
    id: 20014
    name:
      - 甘雨
      - 循循守月
  - 
    id: 20015
    name:
      - 胡桃
      - 雪霁梅香
  - 
    id: 20016
    name:
      - 魈
      - 护法夜叉
  - 
    id: 20017
    name:
      - 夜兰
      - 兰生幽谷
  # 至冬地区
  - 
    id: 20018
    name:
      - 达达利亚
      - 公子
  # 稻妻地区
  - 
    id: 20019
    name:
      - 神里绫华
      - 白鹭霜华
  - 
    id: 20020
    name:
      - 枫原万叶
      - 红叶逐荒波
  - 
    id: 20021
    name:
      - 宵宫
      - 硫焰华舞
  - 
    id: 20022
    name:
      - 雷电将军
      - 一心净土
  - 
    id: 20023
    name:
      - 珊瑚宫心海
      - 真珠之智
  - 
    id: 20024
    name:
      - 八重神子
      - 浮世笑百姿
  - 
    id: 20025
    name:
      - 荒泷一斗
      - 花坂豪快
  - 
    id: 20026
    name:
      - 神里绫人
      - 磐祭叶守