10001:
  info:
    - 蒙德的飞行冠军！
  upGradeMaterial:
    1s:
      燃愿玛瑙碎屑: 1
      小灯草: 3
      牢固的箭簇: 3
    2s:
      燃愿玛瑙断片: 3
      常燃火种: 2
      小灯草: 10
      牢固的箭簇: 15
    3s:
      燃愿玛瑙断片: 5
      常燃火种: 4
      小灯草: 20
      牢固的箭簇: 12