# 更新日志
version:
  "1.0.2":
    - "新增命令 #角色数据"
    - "更新时间: 2022.08.20 17:50"
  "1.0.1":
    - 第一个可用版本完成
    - "修复插件: admin.js"
    - "更新时间: 2022.08.18 22:33"
  "1.0.0":
    - 初版悠懒插件
    - "新增插件: admin.js"
    - "新增插件: pluginManager.js"
    - "更新时间: 2022.08.18 14:37"